plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - 迷[2015-2016].docx
  - 迷[2019autumn].md
  - 迷[2019summer].md
  - 迷[2019winter].md
  - 迷[2022spring].md